[metadata]
name = rules_support
version= attr: rules_support.__version__

author = Baldur van Lew
author_email = b.van_lew@lumc.nl
maintainer = Baldur van Lew
maintainer_email = b.van_lew@lumc.nl

description = Support for HDPS binary naming rules_support
long_description = file: README.md
long_description_content_type = text/markdown
keywords = utility,

license = MIT

classifiers =
    Development Status :: 3 - Alpha
    Environment :: Console
    Intended Audience :: Developers
    Intended Audience :: Information Technology
    License :: OSI Approved :: MIT License
    Natural Language :: English
    Operating System :: OS Independent
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Topic :: Software Development
    Topic :: Utilities

# Using a src/ layout
[options]
package_dir = rules_support
packages=find:
install_requires =
    gitpython
    requests

[flake8]
max-line-length = 99