name: Run Python Tests on master branch (3.7)
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  LKEB_CORE_ACCESS_TOKEN: ${{ secrets.LKEB_CORE_ACCESS_TOKEN }}
  LKEB_CORE_ACCESS_NAME: ${{ secrets.LKEB_CORE_ACCESS_NAME }}

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup git
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - name: Run unittests - TestMix
        run: |
          python -m unittest tests/test_branch_info.py
          python -m unittest tests/test_core_branch_info.py
          python -m unittest tests/test_plugin_branch_info.py